# ============================================================
# scripts/train_model.py
# AI Model Training Script
# Version: 4.0.0 | Date: 08 March 2026
#
# Usage: python scripts/train_model.py --data training_data.csv
#
# This trains the XGBoost signal classifier using historical
# feature data generated by log_features.py or exported from
# Google Sheets + backtesting session.
#
# Target Classes:
#   0 = BUY CALL (CE) — This bar, buying CE within next 60 min hit +25pt target
#   1 = BUY PUT (PE)  — This bar, buying PE within next 60 min hit +25pt target
#   2 = WAIT          — Neither target hit within 60 min (SL hit or no movement)
# ============================================================

import argparse
import json
import os
import sys
import logging
from datetime import datetime

import numpy as np
import pandas as pd
import joblib
from sklearn.model_selection import train_test_split, StratifiedKFold, cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
import xgboost as xgb

logging.basicConfig(level=logging.INFO, format="%(asctime)s | %(levelname)s | %(message)s")
logger = logging.getLogger("train_model")

MODEL_DIR = os.path.join(os.path.dirname(__file__), "..", "models")
os.makedirs(MODEL_DIR, exist_ok=True)

MODEL_PATH = os.path.join(MODEL_DIR, "signal_xgb_v1.pkl")
SCALER_PATH = os.path.join(MODEL_DIR, "feature_scaler.pkl")
FEATURE_LIST_PATH = os.path.join(MODEL_DIR, "feature_list.txt")
REPORT_PATH = os.path.join(MODEL_DIR, "training_report.json")


def load_data(csv_path: str):
    """
    Load training data CSV.
    Expected columns: all feature columns (float) + 'label' column (int: 0/1/2)
    """
    logger.info(f"📂 Loading data from: {csv_path}")
    df = pd.read_csv(csv_path)
    logger.info(f"✅ Loaded {len(df)} rows, {len(df.columns)} columns")

    if "label" not in df.columns:
        raise ValueError("CSV must have a 'label' column (0=CE, 1=PE, 2=WAIT)")

    # Check class distribution
    logger.info(f"📊 Class distribution:\n{df['label'].value_counts()}")
    return df


def train(data_path: str, test_size: float = 0.2):
    """Full training pipeline."""
    df = load_data(data_path)

    # Columns to ignore (labels, timestamps, IDs, and raw text/metadata columns)
    ignore_cols = {
        "label", "timestamp", "date", "sessionDate", "id", "created_at",
        "signal", "reason", "regime", "raw_signal", "rawSignal", "macd_flip",
        "blocked_reason", "engine_version", "engine_mode", "ai_insights",
        "super_trend", "LastFireTime", "LastSignal", "IV_skew_bias",
        "GEX_Regime", "sentiment", "writers_zone", "candle_pattern", "PA_Type", "MACD_status"
    }
    
    # Separate features from label by filtering out ignored columns
    feature_cols = [c for c in df.columns if c not in ignore_cols]
    
    # Drop rows that don't have a label, then build X and y
    df = df.dropna(subset=["label"])
    
    # Attempt to convert to float32 safely
    try:
        X = df[feature_cols].fillna(0).astype(np.float32)
    except ValueError as e:
        # If it still crashes, log which column caused the issue
        logger.error(f"❌ Could not convert features to numbers. Check for text in these columns: {feature_cols}")
        raise e
        
    y = df["label"].astype(int)

    logger.info(f"🔢 Feature count: {len(feature_cols)}")
    logger.info(f"📊 Samples: {len(X)} | Classes: {y.nunique()}")

    # Train/test split (stratified to maintain class ratios)
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=test_size, stratify=y, random_state=42
    )

    # Feature scaling
    scaler = StandardScaler()
    X_train_scaled = scaler.fit_transform(X_train)
    X_test_scaled = scaler.transform(X_test)

    # ---- XGBoost Model ----
    logger.info("🤖 Training XGBoost model...")

    # Class weights to handle imbalance (WAIT is more common)
    class_counts = y_train.value_counts().sort_index()
    total = len(y_train)
    scale_pos_weight = total / (max(1, class_counts.get(0, 1)) * 3)  # Upweight CE/PE

    model = xgb.XGBClassifier(
        n_estimators=500,
        max_depth=6,
        learning_rate=0.05,
        subsample=0.8,
        colsample_bytree=0.8,
        use_label_encoder=False,
        eval_metric="mlogloss",
        objective="multi:softprob",
        num_class=3,
        random_state=42,
        n_jobs=-1,
        early_stopping_rounds=50,
        verbosity=1
    )

    eval_set = [(X_train_scaled, y_train), (X_test_scaled, y_test)]
    model.fit(
        X_train_scaled, y_train,
        eval_set=eval_set,
        verbose=100
    )

    # ---- Evaluation ----
    y_pred = model.predict(X_test_scaled)
    acc = accuracy_score(y_test, y_pred)
    report = classification_report(y_test, y_pred, target_names=["BUY_CE", "BUY_PE", "WAIT"], output_dict=True)
    cm = confusion_matrix(y_test, y_pred).tolist()

    logger.info(f"\n{'='*60}")
    logger.info(f"✅ Test Accuracy: {acc:.4f} ({acc*100:.2f}%)")
    logger.info(f"\n{classification_report(y_test, y_pred, target_names=['BUY_CE', 'BUY_PE', 'WAIT'])}")
    logger.info(f"Confusion Matrix:\n{confusion_matrix(y_test, y_pred)}")
    logger.info(f"{'='*60}")

    # ---- Cross-validation (5-fold) ----
    logger.info("🔁 Running 5-fold cross-validation...")
    cv_scores = cross_val_score(
        xgb.XGBClassifier(n_estimators=200, max_depth=6, learning_rate=0.05,
                          use_label_encoder=False, eval_metric="mlogloss",
                          objective="multi:softprob", num_class=3, random_state=42, n_jobs=-1),
        X.values, y.values, cv=StratifiedKFold(n_splits=5, shuffle=True, random_state=42),
        scoring="accuracy"
    )
    logger.info(f"CV Accuracy: {cv_scores.mean():.4f} ± {cv_scores.std():.4f}")

    # ---- Save Model & Artifacts ----
    joblib.dump(model, MODEL_PATH)
    joblib.dump(scaler, SCALER_PATH)

    with open(FEATURE_LIST_PATH, "w") as f:
        f.write("\n".join(feature_cols))

    # Save training report
    training_report = {
        "trained_at": datetime.now().isoformat(),
        "training_samples": len(X_train),
        "test_samples": len(X_test),
        "feature_count": len(feature_cols),
        "test_accuracy": round(acc, 4),
        "cv_accuracy_mean": round(float(cv_scores.mean()), 4),
        "cv_accuracy_std": round(float(cv_scores.std()), 4),
        "classification_report": report,
        "confusion_matrix": cm,
        "model_path": MODEL_PATH,
        "best_iteration": int(model.best_iteration) if hasattr(model, "best_iteration") else 0,
    }
    with open(REPORT_PATH, "w") as f:
        json.dump(training_report, f, indent=2)

    logger.info(f"\n✅ Model saved: {MODEL_PATH}")
    logger.info(f"✅ Scaler saved: {SCALER_PATH}")
    logger.info(f"✅ Feature list saved: {FEATURE_LIST_PATH}")
    logger.info(f"✅ Training report: {REPORT_PATH}")
    return training_report


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Train NIFTY AI Signal Engine")
    parser.add_argument("--data", required=True, help="Path to training CSV file")
    parser.add_argument("--test-size", type=float, default=0.2, help="Test set fraction (default: 0.2)")
    args = parser.parse_args()

    if not os.path.exists(args.data):
        logger.error(f"❌ Data file not found: {args.data}")
        sys.exit(1)

    result = train(args.data, test_size=args.test_size)
    print(f"\n🎯 Training complete. Accuracy: {result['test_accuracy']*100:.2f}%")
